### ISSUE TITLE
user-agent is not specified when validating the event source

### ISSUE THREAD

**Issue by devigned** [brigadecore/brigade-cloudevents-gateway#71]
The user-agent header is not currently set when validating the event source (https://github.com/brigadecore/brigade-cloudevents-gateway/blob/b4a29d6ae22131a77afd27e6537f047d11e414a8/internal/cloudevents/http/abuse_protection.go#L20-L26). It would be kind to provide some indication of the client when addressing the event source.

**Comment by krancour** [comment]
@devigned do you have a suggestion for an appropriate name for the agent?

**Comment by devigned** [comment]
Perhaps, the following.

```go
userAgent = fmt.Sprintf("Go/%s (%s-%s) brigade-cloudevents-gateway/%s",
		runtime.Version(),
		runtime.GOARCH,
		runtime.GOOS,
		versionNumber,
	)
```

**Comment by krancour** [comment]
Good suggestion. Will amend #78
